# rename this file to config.yaml before start

# qqbot account, not needed anymore for qrcode authentication
account:  2769546520
password: "123"

# server to view verification code, not required for mac
port: 3100
host: localhost

# message handling, ignore offline message 20 min ago
# offline_msg_keeptime: 1200

# plugin list
plugins:
    - help
    - debug
    - apiserver
    - tuling

# apiserver plugin configration
api_port:  3200
api_token: ''

# tuling plugin configration
# æ ¼å¼:å­—ç¬¦ä¸²
tuling_api_key: 'c268de590aed467dba359955708c38c8'
tuling_reply_prefix: 'ğŸ¤–: '
# è§„åˆ™æ ¼å¼~ json(è§„åˆ™:æ­£åˆ™è¡¨è¾¾å¼,å­æŸ¥è¯¢ç´¢å¼•:æ•´æ•°)
# æ­£åˆ™è¡¨è¾¾å¼~ æ²¡æœ‰:() æ‰€æœ‰:(.*) å¤šé¡¹:(a|b|c)
tuling_whitelist_group: '{"rule":"(202892015|287156946|417727807)","matchindex":1}'
tuling_whitelist_user: '{"rule":"(.*)","matchindex":1}'
tuling_whitelist_keyword: '{"rule":"(@è°·å¦¹|@è°·å“¥)(.*)","matchindex":2}'
tuling_blacklist_group: '{"rule":"()","matchindex":1}'
tuling_blacklist_user: '{"rule":"(903338544)","matchindex":1}'
tuling_blacklist_keyword: '{"rule":"(æŠ¥ç‚¹|æŠ¥æ—¶)(.*)","matchindex":1}'
